server:
  port: 8899
fdfs:
  connect-timeout: 10000
  so-timeout: 3000
  tracker-list:
    - 192.168.80.242:22122
spring:
  datasource:
    url: jdbc:mysql://10.10.90.145:3306/shopping?useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  servlet:
    multipart:
      max-request-size: 10MB